language: python
sudo: false
cache: pip

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install -e ".[test,docs]"

script:
  - pytest --doctest-modules --cov=adopy
  - codecov --token $CODECOV_TOKEN
  # - travis-sphinx build

after_success:
  # - travis-sphinx deploy
  - flake8 adopy --format=pylint --statistics --exit-zero
  - pylint adopy --rcfile=setup.cfg --exit-zero

