language: python
sudo: false
cache: pip

python:
  - "2.7"
  - "3.5"
  - "3.6"

install:
  - pip install -e .[test]

script:
  - flake8 adopy --format=pylint --statistics
  - pytest --doctest-modules --cov=adopy
  - codecov --token $CODECOV_TOKEN
