language: python
sudo: false
cache: pip

branches:
  only:
  - master
  - develop

python:
  - "2.7"
  - "3.5"
  - "3.6"

install:
  - pip install .[test]

script:
  - flake8 adopy --format=pylint --statistics --exit-zero
  - pytest --cov=adopy
  - codecov --token $CODECOV_TOKEN
