language: python
sudo: false
cache: pip

branches:
  only:
  - master
  - develop
  - hotfix/*

python:
  - "2.7"
  - "3.5"
  - "3.6"

install:
  - pip install -e .[test]

script:
  - flake8 adopy --format=pylint --statistics
  - pytest --cov=adopy
  - codecov --token $CODECOV_TOKEN
