dist: xenial
language: python
sudo: false
cache: pip

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8-dev"

install: "make"

script:
  - make test-travis

after_success:
  - make lint
  - make docs-travis

