[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "adopy"
dist-name = "ADOpy"
author = "Jaeyeong Yang"
author-email = "jaeyeong.yang1125@gmail.com"
home-page = "https://github.com/JaeyeongYang/adopy/"

requires = [
    "numpy",
    "pandas",
    "scipy",
]
requires-python = ">=3.5"

description-file = "README.rst"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.5",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3 :: Only",
]

